# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hi": "00_core.ipynb",
         "say_hello": "01_nbtest.ipynb"}

modules = ["core.py",
           "nbtest.py"]

doc_url = "https://stevenborg.github.io/nbtest/"

git_url = "https://github.com/stevenborg/nbtest/tree/master/"

def custom_doc_links(name): return None
