# AUTOGENERATED! DO NOT EDIT! File to edit: 01_nbtest.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'do_something']

# Cell
def say_hello(name):
    "Say Hello generically"
    print('Hello!')

# Cell
def do_something():
    "Do something"
    print('Doing something!')

do_something()